
export const blogPosts = [
    {
        id: 868323,
        title: 'Top 10 Cricket Moments of 2024',
        excerpt: 'Relive the most exciting moments from this year\'s cricket matches, from stunning catches to nail-biting finishes. We\'ve compiled the very best that the cricketing world has offered in 2024.',
        imageUrl: 'https://imgs.search.brave.com/si4Y-HfJpxcUG4SvKJ8umugj19dr8UTXeW7qQXT5H7M/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvMjE1/OTg0NTI5Mi9waG90/by9icmlkZ2V0b3du/LWJhcmJhZG9zLXBs/YXllcnMtb2YtaW5k/aWEtY2VsZWJyYXRl/LWFmdGVyLXRoZXkt/ZGVmZWF0ZWQtc291/dGgtYWZyaWNhLXRv/LXdpbi10aGUuanBn/P3M9NjEyeDYxMiZ3/PTAmaz0yMCZjPUpm/UHVoUklYXy1qNGVo/QUhiODNqeUFHay11/eXl0NEpyQWR2X1R2/eE8zaUE9',
        date: 'May 15, 2024',
        category: 'Highlights',
        author: 'John Smith',
        readTime: '8 min read',
        tags: ['Cricket', '2024', 'Highlights', 'Top Moments']
    },
    {
        id: 234446,
        title: 'Rising Stars: Young Cricketers to Watch',
        excerpt: 'Meet the upcoming talent that\'s set to take the cricket world by storm. These young players are making waves with their exceptional skills and are poised to become the next generation of cricket superstars.',
        imageUrl: 'https://imgs.search.brave.com/P2bgXmthOJF_pN6w2jTGjurIu5RonzCsvuK5O_lTjRQ/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly93d3cu/YWxqYXplZXJhLmNv/bS93cC1jb250ZW50/L3VwbG9hZHMvMjAy/NC8wNi9BRlBfXzIw/MjQwNjI5X18zNFpW/M0UzX192MV9fSGln/aFJlc19fQ3JpY2tl/dE1lblNUMjBXb3Js/ZEN1cEZpbmFsSW5k/aWFWU291dGhBZnJp/Y2EtMTcxOTY4NjI0/OC5qcGc_dz03NzAm/cmVzaXplPTc3MCw1/MTM',
        date: 'May 12, 2024',
        category: 'Player Spotlight',
        author: 'Sarah Johnson',
        readTime: '6 min read',
        tags: ['Young Talent', 'Future Stars', 'Cricket']
    },
    {
        id: 276546,
        title: 'The Evolution of T20 Cricket',
        excerpt: 'How the shortest format of the game has changed cricket forever. Explore the impact of T20 on player skills, strategies, and the sport\'s global appeal. We dive deep into the transformation of cricket in the T20 era.',
        imageUrl: 'https://imgs.search.brave.com/XV5LeSfLR5vj9R6p6VtWzJ0pQlU3N91vh8iZ3CzHr4E/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMuaWNjLWNyaWNr/ZXQuY29tL2ltYWdl/L3VwbG9hZC90X3Jh/dGlvM180LXNpemUy/MC92MTcxOTg2MDU4/Mi9wcmQvanVrY20y/ZnVvaWViank3aXJ4/Zjg.jpeg',
        date: 'May 10, 2024',
        category: 'Analysis',
        author: 'Michael Lee',
        readTime: '10 min read',
        tags: ['T20', 'Cricket Evolution', 'Strategy']
    },
];

export const liveMatches = [
    {
        teams: 'India vs Australia',
        score: 'IND 280/4 (45 ov)',
        status: 'Live',
        team1Code: 'IN',
        team2Code: 'AU',
        matchId: 1
    },
    {
        teams: 'England vs South Africa',
        score: 'ENG 220/7 (38 ov)',
        status: 'Live',
        team1Code: 'GB',
        team2Code: 'ZA',
        matchId: 2
    },
    {
        teams: 'New Zealand vs West Indies',
        score: 'NZ 180/3 (30 ov)',
        status: 'Live',
        team1Code: 'NZ',
        team2Code: 'WI',
        matchId: 5
    },
    {
        teams: 'Pakistan vs Sri Lanka',
        score: 'PAK 150/2 (25 ov)',
        status: 'Live',
        team1Code: 'PK',
        team2Code: 'LK',
        matchId: 3
    },
    {
        teams: 'Bangladesh vs Afghanistan',
        score: 'BAN 200/5 (35 ov)',
        status: 'Live',
        team1Code: 'BD',
        team2Code: 'AF',
        matchId: 4
    },
    {
        teams: 'Zimbabwe vs Ireland',
        score: 'ZIM 120/1 (20 ov)',
        status: 'Live',
        team1Code: 'ZW',
        team2Code: 'IE',
        matchId: 8
    },
    {
        teams: 'Netherlands vs Scotland',
        score: 'NED 90/3 (15 ov)',
        status: 'Live',
        team1Code: 'NL',
        team2Code: 'GB-SCT',
        matchId: 7
    },
];

export const teams = [
    { value: "india", label: "India", flag: "IN" },
    { value: "australia", label: "Australia", flag: "AU" },
    { value: "england", label: "England", flag: "GB" },
    { value: "southAfrica", label: "South Africa", flag: "ZA" },
];


export const formats = [
    { value: "test", label: "Test" },
    { value: "odi", label: "ODI" },
    { value: "t20", label: "T20" },
];

export const seasons = [
    { value: "2023", label: "2023" },
    { value: "2022", label: "2022" },
    { value: "2021", label: "2021" },
];

export const tournaments = [
    { value: "ipl", label: "IPL" },
    { value: "worldCup", label: "World Cup" },
    { value: "t20WorldCup", label: "T20 World Cup" },
];

export const stats = [
    { value: "runs", label: "Runs" },
    { value: "wickets", label: "Wickets" },
    { value: "fifties", label: "Fifties" },
    { value: "sixes", label: "Sixes" },
    { value: "strikeRate", label: "Strike Rate" },
];
export const initBattingStats = [
    {
        rank: 1,
        player: "Virat Kohli",
        team: "India",
        countryCode: "IN",
        matches: 254,
        innings: 242,
        runs: 12169,
        average: 59.07,
        strikeRate: 93.17,
        hundreds: 43,
        fifties: 58,
    },
    {
        rank: 2,
        player: "Rohit Sharma",
        team: "India",
        countryCode: "IN",
        matches: 227,
        innings: 220,
        runs: 9205,
        average: 48.96,
        strikeRate: 88.90,
        hundreds: 29,
        fifties: 43,
    },
    {
        rank: 3,
        player: "Steve Smith",
        team: "Australia",
        countryCode: "AU",
        matches: 128,
        innings: 124,
        runs: 4378,
        average: 42.46,
        strikeRate: 85.46,
        hundreds: 11,
        fifties: 25,
    },
    {
        rank: 4,
        player: "Kane Williamson",
        team: "New Zealand",
        countryCode: "NZ",
        matches: 151,
        innings: 144,
        runs: 6173,
        average: 47.83,
        strikeRate: 81.75,
        hundreds: 13,
        fifties: 39,
    },
    {
        rank: 5,
        player: "David Warner",
        team: "Australia",
        countryCode: "AU",
        matches: 128,
        innings: 125,
        runs: 5455,
        average: 45.37,
        strikeRate: 95.76,
        hundreds: 18,
        fifties: 24,
    },
    {
        rank: 6,
        player: "Joe Root",
        team: "England",
        countryCode: "GB",
        matches: 152,
        innings: 145,
        runs: 6109,
        average: 51.34,
        strikeRate: 87.36,
        hundreds: 16,
        fifties: 36,
    },
    {
        rank: 7,
        player: "Babar Azam",
        team: "Pakistan",
        countryCode: "PK",
        matches: 74,
        innings: 72,
        runs: 3359,
        average: 56.61,
        strikeRate: 87.09,
        hundreds: 11,
        fifties: 15,
    },
    {
        rank: 8,
        player: "Quinton de Kock",
        team: "South Africa",
        countryCode: "ZA",
        matches: 121,
        innings: 118,
        runs: 5200,
        average: 44.14,
        strikeRate: 95.29,
        hundreds: 15,
        fifties: 26,
    },
    {
        rank: 9,
        player: "Faf du Plessis",
        team: "South Africa",
        countryCode: "ZA",
        matches: 143,
        innings: 135,
        runs: 5507,
        average: 47.47,
        strikeRate: 88.60,
        hundreds: 12,
        fifties: 35,
    },
    {
        rank: 10,
        player: "Ross Taylor",
        team: "New Zealand",
        countryCode: "NZ",
        matches: 233,
        innings: 217,
        runs: 8026,
        average: 47.01,
        strikeRate: 83.40,
        hundreds: 21,
        fifties: 51,
    },
    {
        rank: 11,
        player: "Shikhar Dhawan",
        team: "India",
        countryCode: "IN",
        matches: 145,
        innings: 142,
        runs: 6105,
        average: 45.96,
        strikeRate: 93.55,
        hundreds: 17,
        fifties: 32,
    },
    {
        rank: 12,
        player: "Aaron Finch",
        team: "Australia",
        countryCode: "AU",
        matches: 129,
        innings: 127,
        runs: 5232,
        average: 41.10,
        strikeRate: 88.92,
        hundreds: 17,
        fifties: 26,
    },
];
export const initBowlingStats = [
    {
        rank: 1,
        player: "Mitchell Starc",
        team: "Australia",
        countryCode: "AU",
        matches: 100,
        innings: 98,
        wickets: 195,
        average: 22.23,
        economy: 4.85,
        strikeRate: 27.4,
        best: "6/28",
        fiveWickets: 8,
    },
    {
        rank: 2,
        player: "Jasprit Bumrah",
        team: "India",
        countryCode: "IN",
        matches: 67,
        innings: 65,
        wickets: 108,
        average: 24.39,
        economy: 4.49,
        strikeRate: 32.6,
        best: "5/27",
        fiveWickets: 2,
    },
    {
        rank: 3,
        player: "Trent Boult",
        team: "New Zealand",
        countryCode: "NZ",
        matches: 93,
        innings: 91,
        wickets: 169,
        average: 25.16,
        economy: 4.74,
        strikeRate: 31.7,
        best: "7/34",
        fiveWickets: 5,
    },
    {
        rank: 4,
        player: "Kagiso Rabada",
        team: "South Africa",
        countryCode: "ZA",
        matches: 81,
        innings: 78,
        wickets: 126,
        average: 27.37,
        economy: 4.98,
        strikeRate: 33.0,
        best: "6/16",
        fiveWickets: 2,
    },
    {
        rank: 5,
        player: "Pat Cummins",
        team: "Australia",
        countryCode: "AU",
        matches: 73,
        innings: 70,
        wickets: 111,
        average: 27.92,
        economy: 5.16,
        strikeRate: 32.4,
        best: "5/70",
        fiveWickets: 1,
    },
    {
        rank: 6,
        player: "Rashid Khan",
        team: "Afghanistan",
        countryCode: "AF",
        matches: 80,
        innings: 79,
        wickets: 140,
        average: 18.57,
        economy: 4.16,
        strikeRate: 26.8,
        best: "7/18",
        fiveWickets: 4,
    },
    {
        rank: 7,
        player: "Mujeeb Ur Rahman",
        team: "Afghanistan",
        countryCode: "AF",
        matches: 55,
        innings: 54,
        wickets: 85,
        average: 23.36,
        economy: 3.94,
        strikeRate: 35.5,
        best: "5/50",
        fiveWickets: 1,
    },
    {
        rank: 8,
        player: "Imran Tahir",
        team: "South Africa",
        countryCode: "ZA",
        matches: 107,
        innings: 106,
        wickets: 173,
        average: 24.83,
        economy: 4.65,
        strikeRate: 32.0,
        best: "7/45",
        fiveWickets: 3,
    },
    {
        rank: 9,
        player: "Mohammad Shami",
        team: "India",
        countryCode: "IN",
        matches: 79,
        innings: 78,
        wickets: 144,
        average: 25.42,
        economy: 5.40,
        strikeRate: 28.2,
        best: "5/69",
        fiveWickets: 1,
    },
    {
        rank: 10,
        player: "Lockie Ferguson",
        team: "New Zealand",
        countryCode: "NZ",
        matches: 45,
        innings: 45,
        wickets: 77,
        average: 25.39,
        economy: 5.51,
        strikeRate: 27.6,
        best: "5/45",
        fiveWickets: 1,
    },
    {
        rank: 11,
        player: "Shaheen Afridi",
        team: "Pakistan",
        countryCode: "PK",
        matches: 30,
        innings: 29,
        wickets: 59,
        average: 23.67,
        economy: 5.45,
        strikeRate: 26.1,
        best: "6/35",
        fiveWickets: 2,
    },
    {
        rank: 12,
        player: "Adil Rashid",
        team: "England",
        countryCode: "GB",
        matches: 111,
        innings: 109,
        wickets: 159,
        average: 31.78,
        economy: 5.60,
        strikeRate: 34.0,
        best: "5/27",
        fiveWickets: 1,
    },
];

export const sampleCountries = [
    { name: "India", code: "IN" },
    { name: "Australia", code: "AU" },
    { name: "United Kingdom", code: "GB" },
    { name: "South Africa", code: "ZA" },
    { name: "New Zealand", code: "NZ" },
    // Add more countries as needed
];